version: '3.8'
services:
  cerebro:
    image: lmenezes/cerebro
    container_name: cerebro
    ports:
      - "9000:9000"
    environment:
      ELASTICSEARCH_HOST: "http://esm01:9200"
      CEREBRO_PORT: 9000

networks:
  default:
    external:
      name: logging