filebeat.config.modules:
  enabled: true
  reload.enabled: false
  reload.period: 10s
  path: ${path.config}/modules.d/*.yml

filebeat.inputs:
- type: filestream
  paths:
    - /var/log/nginx/*.log
  fields:
    nginx: true

#filebeat.modules:
#  - module: nginx
#    access:
#      enabled: true
#      var.paths:
#        - /var/log/nginx/access.log
#    error:
#      enabled: true
#      var.paths:
#        - /var/log/nginx/error.log
#    ingress_controller:
#      enabled: false

setup:
  kibana:
    host: "http://kibana:5601"
  dashboards:
    enabled: true

output:
  elasticsearch:
    enabled: false
    hosts: ["esm01:9200"]
  logstash:
    enabled: true
    hosts: ["logstash:5044"]
